data to changelog added
ruljin/CodersCamp2020.Project.TypeScript.YahtzeeGame pull request #20
Opened 2021-01-29 15:15 UTC by brzeczkowskaw

2021-01-29 18:02 UTC, Mrozelek requested changes

2021-01-29 18:02 UTC, Mrozelek commented on src/components/intro/intro.ts
> +    return createElementFromString(`<main>
`<main>` tag is used to specify the main content of the `<body>`. What if I would like to use this component, but also the other one or if I would like to use this component twice?

2021-01-29 22:18 UTC, Mrozelek requested changes

2021-01-29 22:18 UTC, Mrozelek commented on src/components/intro/intro.ts
>          <div class="container">
Last thing. Instead of wrapping `<div>` with `<section>` just use this `<section>` with `class="container"`. Same comes for tests.

2021-01-30 17:14 UTC, Mrozelek approved these changes

2021-01-30 18:30 UTC, kami3la approved these changes

2021-01-30 18:42 UTC, merged