Feature/labels
ruljin/CodersCamp2020.Project.TypeScript.YahtzeeGame pull request #21
Opened 2021-01-29 15:55 UTC by kami3la

2021-01-29 17:56 UTC, Mrozelek requested changes

2021-01-29 17:56 UTC, Mrozelek commented on CHANGELOG.md
> +- Labels Component.
Why is it plural?

2021-01-29 17:56 UTC, Mrozelek commented on src/components/labels/labels.scss
> +.labels {
Why is it plural?

2021-01-29 17:56 UTC, Mrozelek commented on src/components/labels/labels.ts
> +class LabelsComponent implements WebComponent {
Why is it plural?

2021-01-29 17:56 UTC, Mrozelek commented on src/components/labels/labels.scss
> +  &__settings-style {
Is there a reason to call this style `style`? We all know it is indeed a style.

2021-01-29 17:56 UTC, Mrozelek commented on src/components/labels/labels.ts
> +  private componentElement: string = '';
You didn't use `yarn lint` command.

2021-01-29 17:56 UTC, Mrozelek commented on src/components/labels/labels.ts
> +    return this.componentElement;
Just use the constructor to specify the text in label. What if I would like to have label with 20 different texts? Would I create a method for each text?

2021-01-30 18:20 UTC, adax10 approved these changes

2021-01-30 18:29 UTC, Mrozelek approved these changes

2021-01-30 21:06 UTC, brzeczkowskaw approved these changes

2021-01-30 21:17 UTC, merged