authors component added
ruljin/CodersCamp2020.Project.TypeScript.YahtzeeGame pull request #22
Opened 2021-01-29 16:06 UTC by brzeczkowskaw

2021-01-29 17:39 UTC, Mrozelek requested changes

2021-01-29 17:39 UTC, Mrozelek commented on src/components/authors/authors.scss
> +}
This is not how BEM works. You are not supposed to style tags unless you have a very good reason.

2021-01-29 17:39 UTC, Mrozelek commented on src/components/authors/authors.ts
> +    return createElementFromString(`<main>
`<main>` tag is used to specify the main content of the `<body>`. What if I would like to use this component, but also the other one or if I would like to use this component twice?

2021-01-30 09:44 UTC, Mrozelek requested changes

2021-01-30 09:44 UTC, Mrozelek commented on src/components/authors/authors.ts
>          <div class="container">
Instead of wrapping `<div>` with `<section>` just use this `<section>` with class="container". Same comes for tests.

2021-01-30 17:27 UTC, Mrozelek approved these changes

2021-01-30 18:27 UTC, adax10 approved these changes

2021-01-30 18:34 UTC, kami3la approved these changes

2021-01-30 18:34 UTC, merged